
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [4]:
import numpy as np
ar_r = np.arange(10)
print(ar_r)

[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [6]:
ar_r=np.arange(9).reshape(3,3)
print (ar_r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [3]:
import numpy as np
ar_r=np.arange(9).reshape(3,3)
element=ar_r[1,1]
print(element)

4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [12]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
addation=np.add(array1,array2)
print (addation)


[5 7 9]


In [13]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
subtraction=np.subtract(array1,array2)
print (subtraction)


[-3 -3 -3]


In [14]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
multiplication=np.multiply(array1,array2)
print (multiplication)


[ 4 10 18]


In [15]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
division=np.divide(array1,array2)
print (division)


[0.25 0.4  0.5 ]


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [18]:
array3=np.array([1, 2, 3, 4, 5, 6])
reshape_arr=np.reshape(array3,(2,3))
print(reshape_arr)


[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [19]:
ran_array=np.random.randint (low=0 , high=50 , size=(5,5))
print(ran_array)

[[11 31 23 47  7]
 [25 31  7 17 42]
 [49 47 12 42 25]
 [17 48 24 14  8]
 [ 1 23 12 12 31]]


Replace all values in the sub-array with a specific value.


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [8]:
import numpy as np
number = np.arange(3)
print (number)
print()
array2d = np.tile(number, (3, 1))
print(array2d)


[0 1 2]

[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [4]:
array1D=np.array([1,2,3])
result=array2d+array1D
print(result)

[[1 3 5]
 [1 3 5]
 [1 3 5]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [20]:
array2D1=np.random.randint(0,10, size=(3,3))
print(array2D1)
print()
array2D2=np.random.randint(0,10, size=(3,3))
print(array2D2)


[[3 8 2]
 [4 8 9]
 [6 3 7]]

[[2 0 9]
 [8 5 4]
 [6 9 3]]


In [2]:
import numpy as np
array2D1=np.random.randint(0,10, size=(3,3))
print(array2D1)
print()
array2D2=np.random.randint(0,10, size=(3,3))
print(array2D2)
#concatenate
Horizontally=np.concatenate((array2D1,array2D2), axis=1)
vertically=np.concatenate((array2D1,array2D2), axis=0)
print(Horizontally)
print()
print(vertically)

[[4 6 8]
 [9 8 8]
 [3 7 4]]

[[6 4 2]
 [8 3 5]
 [4 0 9]]
[[4 6 8 6 4 2]
 [9 8 8 8 3 5]
 [3 7 4 4 0 9]]

[[4 6 8]
 [9 8 8]
 [3 7 4]
 [6 4 2]
 [8 3 5]
 [4 0 9]]


In [ ]:
import numpy as np
array2D1=np.random.randint(0,10, size=(3,3))
print(array2D1)
print()
array2D2=np.random.randint(0,10, size=(3,3))
print(array2D2)
#concatenate
Horizontally=np.concatenate((array2D1,array2D2), axis=1)
vertically=np.concatenate((array2D1,array2D2), axis=0)
print(Horizontally)
print()
print(vertically)
print()
# horizontal spilt

array2D1_h_split,array2D2_h_split = np.hsplit(Horizontally ,2)
print(array2D1_h_split)
print()
print(array2D2_h_split)
#vertically split
array2D1_v_split,array2D2_v_split = np.vsplit(vertically ,2)
print(array2D1_v_split)
print()
print(array2D2_v_split)


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

